server:
  port: 80

eureka:
  client:
    service-url:
      defualtZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: false

feign:
  hystrix:
    enabled: true