server:
  port: 8002
eureka:
  instance:
    instance-id: payment8002
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: cloud-payment-service
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.bean
