server:
  port: 8401
spring:
  application:
    name: cloud-sentinel-com.cloud.bean.service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
